"""Initial schema: tenancy, documents, printing, storage, retention, billing, audit.

Written by hand from ``app/models/`` rather than autogenerated: the schema had to
exist before any database did.

Revision ID: 0001
Revises:
Create Date: 2026-09-18
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())
NOW = sa.text("now()")


def _timestamps() -> tuple[sa.Column, sa.Column]:
    return (
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
    )


def _tenant_columns() -> tuple[sa.Column, sa.Column]:
    return (
        sa.Column("mm_id", UUID, nullable=False),
        sa.Column("site_id", UUID, nullable=False),
    )


def _tenant_foreign_keys() -> tuple[sa.ForeignKeyConstraint, sa.ForeignKeyConstraint]:
    return (
        sa.ForeignKeyConstraint(["mm_id"], ["mms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
    )


def upgrade() -> None:
    _create_tenancy()
    _create_billing()
    _create_catalogues()
    _create_storage_and_retention()
    _create_documents()
    _create_printing()
    _create_audit()


def _create_tenancy() -> None:
    op.create_table(
        "mms",
        sa.Column("id", UUID, nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("tax_id", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_mms"),
        sa.UniqueConstraint("slug", name="uq_mms_slug"),
    )

    op.create_table(
        "sites",
        sa.Column("id", UUID, nullable=False),
        sa.Column("mm_id", UUID, nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("site_prefix", sa.String(length=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["mm_id"], ["mms.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name="pk_sites"),
        sa.UniqueConstraint("mm_id", "site_prefix", name="uq_sites_mm_id_site_prefix"),
    )
    op.create_index("ix_sites_mm_id", "sites", ["mm_id"])

    op.create_table(
        "users",
        sa.Column("id", UUID, nullable=False),
        sa.Column("mm_id", UUID, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("default_site_id", UUID, nullable=True),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["mm_id"], ["mms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["default_site_id"], ["sites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    op.create_index("ix_users_mm_id_email", "users", ["mm_id", "email"], unique=True)

    op.create_table(
        "user_sites",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("site_id", UUID, nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("extra_permissions", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_user_sites"),
        sa.UniqueConstraint("user_id", "site_id", name="uq_user_sites_user_id_site_id"),
    )
    op.create_index("ix_user_sites_site_id", "user_sites", ["site_id"])


def _create_billing() -> None:
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_es", sa.String(length=80), nullable=False),
        sa.Column("name_en", sa.String(length=80), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("limits", JSONB, nullable=False),
        sa.Column("stripe_price_id", sa.String(length=120), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("code", name="pk_plans"),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", UUID, nullable=False),
        sa.Column("mm_id", UUID, nullable=False),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=120), nullable=True),
        sa.Column("provider_subscription_id", sa.String(length=120), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("limit_overrides", JSONB, nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["mm_id"], ["mms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_code"], ["plans.code"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name="pk_subscriptions"),
        sa.UniqueConstraint("mm_id", name="uq_subscriptions_mm_id"),
    )
    op.create_index("ix_subscriptions_plan_code", "subscriptions", ["plan_code"])

    op.create_table(
        "usage_counters",
        sa.Column("id", UUID, nullable=False),
        sa.Column("mm_id", UUID, nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("documents_uploaded", sa.Integer(), nullable=False),
        sa.Column("labels_printed", sa.Integer(), nullable=False),
        sa.Column("bytes_stored", sa.BigInteger(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["mm_id"], ["mms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_usage_counters"),
        sa.UniqueConstraint("mm_id", "period", name="uq_usage_counters_mm_id_period"),
    )


def _create_catalogues() -> None:
    op.create_table(
        "deca_field_definitions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label_es", sa.String(length=160), nullable=False),
        sa.Column("label_en", sa.String(length=160), nullable=False),
        sa.Column("help_es", sa.Text(), nullable=True),
        sa.Column("help_en", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=16), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("pattern", sa.String(length=255), nullable=True),
        sa.Column("choices", sa.Text(), nullable=True),
        sa.Column("legal_reference", sa.String(length=160), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("catalog_version", sa.Integer(), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("code", name="pk_deca_field_definitions"),
    )


def _create_storage_and_retention() -> None:
    op.create_table(
        "storage_backends",
        sa.Column("id", UUID, nullable=False),
        *_tenant_columns(),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("config", JSONB, nullable=False),
        sa.Column("config_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_health_ok", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        *_tenant_foreign_keys(),
        sa.PrimaryKeyConstraint("id", name="pk_storage_backends"),
    )
    op.create_index(
        "ix_storage_backends_tenant",
        "storage_backends",
        ["mm_id", "site_id", "created_at"],
    )

    op.create_table(
        "retention_policies",
        sa.Column("id", UUID, nullable=False),
        *_tenant_columns(),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("legal_basis", sa.String(length=255), nullable=True),
        sa.Column("warn_days_before", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        *_tenant_foreign_keys(),
        sa.PrimaryKeyConstraint("id", name="pk_retention_policies"),
    )
    op.create_index(
        "ix_retention_policies_tenant",
        "retention_policies",
        ["mm_id", "site_id", "created_at"],
    )


def _create_documents() -> None:
    op.create_table(
        "documents",
        sa.Column("id", UUID, nullable=False),
        *_tenant_columns(),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_backend_id", UUID, nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("deca", JSONB, nullable=False),
        sa.Column("deca_status", sa.String(length=16), nullable=False),
        sa.Column("deca_catalog_version", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("compliance_status", sa.String(length=16), nullable=False),
        sa.Column("has_text_layer", sa.Boolean(), nullable=True),
        sa.Column("qr_embedded", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", UUID, nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by_id", UUID, nullable=True),
        sa.Column("retention_policy_id", UUID, nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_reason", sa.String(length=255), nullable=True),
        sa.Column("print_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        *_tenant_foreign_keys(),
        sa.ForeignKeyConstraint(
            ["storage_backend_id"], ["storage_backends.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["supersedes_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["retention_policy_id"], ["retention_policies.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_documents"),
    )
    op.create_index("ix_documents_tenant", "documents", ["mm_id", "site_id", "created_at"])
    op.create_index("ix_documents_sha256", "documents", ["mm_id", "site_id", "sha256"])
    op.create_index("ix_documents_expires_at", "documents", ["expires_at"])
    op.create_index("ix_documents_storage_backend_id", "documents", ["storage_backend_id"])

    op.create_table(
        "share_tokens",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_share_tokens"),
        sa.UniqueConstraint("token", name="uq_share_tokens_token"),
    )
    op.create_index("ix_share_tokens_document_id", "share_tokens", ["document_id"])

    op.create_table(
        "document_accesses",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("share_token_id", UUID, nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["share_token_id"], ["share_tokens.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name="pk_document_accesses"),
    )
    op.create_index(
        "ix_document_accesses_document",
        "document_accesses",
        ["document_id", "accessed_at"],
    )


def _create_printing() -> None:
    op.create_table(
        "print_queue_items",
        sa.Column("id", UUID, nullable=False),
        *_tenant_columns(),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        *_tenant_foreign_keys(),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_print_queue_items"),
    )
    op.create_index(
        "ix_print_queue_owner",
        "print_queue_items",
        ["mm_id", "site_id", "user_id", "position"],
    )

    op.create_table(
        "print_jobs",
        sa.Column("id", UUID, nullable=False),
        *_tenant_columns(),
        sa.Column("user_id", UUID, nullable=True),
        sa.Column("printer_name", sa.String(length=160), nullable=True),
        sa.Column("layout", sa.String(length=16), nullable=False),
        sa.Column("template_code", sa.String(length=64), nullable=False),
        sa.Column("start_position", sa.Integer(), nullable=False),
        sa.Column("label_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        *_timestamps(),
        *_tenant_foreign_keys(),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name="pk_print_jobs"),
    )
    op.create_index("ix_print_jobs_tenant", "print_jobs", ["mm_id", "site_id", "created_at"])

    op.create_table(
        "print_job_items",
        sa.Column("id", UUID, nullable=False),
        sa.Column("print_job_id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column("label_index", sa.Integer(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["print_job_id"], ["print_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_print_job_items"),
    )
    op.create_index(
        "ix_print_job_items_document",
        "print_job_items",
        ["document_id", "created_at"],
    )
    op.create_index("ix_print_job_items_print_job_id", "print_job_items", ["print_job_id"])


def _create_audit() -> None:
    op.create_table(
        "audit_logs",
        sa.Column("id", UUID, nullable=False),
        sa.Column("mm_id", UUID, nullable=True),
        sa.Column("site_id", UUID, nullable=True),
        sa.Column("actor_user_id", UUID, nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=48), nullable=False),
        sa.Column("object_id", UUID, nullable=True),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name="pk_audit_logs"),
    )
    op.create_index("ix_audit_logs_tenant", "audit_logs", ["mm_id", "site_id", "created_at"])
    op.create_index("ix_audit_logs_object", "audit_logs", ["object_type", "object_id"])


def downgrade() -> None:
    for table in (
        "audit_logs",
        "print_job_items",
        "print_jobs",
        "print_queue_items",
        "document_accesses",
        "share_tokens",
        "documents",
        "retention_policies",
        "storage_backends",
        "deca_field_definitions",
        "usage_counters",
        "subscriptions",
        "plans",
        "user_sites",
        "users",
        "sites",
        "mms",
    ):
        op.drop_table(table)
